name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: mystorius/hf-cloud-mle
  DOCKER_IMAGE_TAG: dev


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Registry
      - name: Log in to Docker Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: |
          cd part2
          docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

      # Step 4: Push the dev Docker image to the registry
      - name: Push the dev Docker image
        run: |
          docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

  test:
    runs-on: ubuntu-latest # Here you would use a GPU-enabled runner
    needs: build  # Ensure this job runs after the build job

    steps:
      # Step 1: Check out the code (again)
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Registry
      - name: Log in to Docker Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 3: Pull the dev Docker image
      - name: Pull the dev Docker image
        run: |
          docker pull $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

      # Step 4: Test the Docker image locally with GPU
      - name: Test the Docker image
        id: test_image
        run: |
          if docker run --gpus=all $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG; then
            echo "Docker container ran successfully with GPU support."
            echo "::set-output name=result::success"  # Set output for the next step
          else
            echo "GPU support not available. Running without GPU..."
            docker run $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
            echo "::set-output name=result::failure"  # Set output for the next step
          fi

      # Step 5: Tag and Push the latest Docker image if tests passed
      - name: Tag and Push the latest Docker image
        if: steps.test_image.outputs.result == 'success'  # Only run if the tests pass
        run: |
          docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG mystorius/hf-cloud-mle:latest
          docker push mystorius/hf-cloud-mle:latest
